"""Local Workshop custom game: start from a saved 5:00 state and play to 10:00.

    python workshop.py install          write the addon into Dota's dota_addons folder
    python workshop.py save [session]   save your state (level, skills, items, gold) from a recorded
                                        session at 5:00 (default: the latest one where you were level 6+)
    python workshop.py play             launch Dota (Workshop Tools) straight into the drill

In the drill: Tinker, Radiant, no enemy heroes. The addon fast-forwards the first 5 minutes at
10x while you're held in fountain (so camps, waves and runes are in their natural 5:00 state and
the coach's benchmarks line up), puts your saved state back at 4:55, refreshes you, and ends the
game at 10:00. Needs Dota 2 Workshop Tools (Steam > Dota 2 > DLC).
"""
from __future__ import annotations

import glob
import json
import os
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).parent
ADDON = "tinker_drill"
SAMPLE_MATCHES = {"9020212922", "9020204172", "9016088490"}   # games in samples/ (simulator runs)
STEAM = pathlib.Path(r"C:\Program Files (x86)\Steam")
DOTA = STEAM / "steamapps" / "common" / "dota 2 beta"
GAME_DIR = DOTA / "game" / "dota_addons" / ADDON
CONTENT_DIR = DOTA / "content" / "dota_addons" / ADDON

DEFAULT_STATE = {
    "source": "default level-6 Tinker",
    "level": 6,
    "abilities": {"tinker_laser": 1, "tinker_march_of_the_machines": 3, "tinker_keen_teleport": 1, "tinker_rearm": 1},
    "items": ["item_bottle", "item_null_talisman", "item_branches", "item_branches", "item_tpscroll"],
    "gold": 400,
}

ADDONINFO = '''"AddonInfo"
{
	"maps"			"dota"
	"IsPlayable"	"1"
}
'''

LUA = r'''-- Tinker Coach drill: Tinker from a saved 5:00 state, play until 10:00.
-- Generated by tinker_coach/workshop.py. The saved state lives in drill_state.lua.
local STATE = require("drill_state")
STATE.start_at = STATE.start_at or 300
STATE.end_at = STATE.end_at or 600
STATE.speed = STATE.speed or 10

if CTinkerDrill == nil then
	_G.CTinkerDrill = class({})
end

function Precache(context)
	PrecacheUnitByNameSync("npc_dota_hero_tinker", context)
end

function Activate()
	GameRules.tinkerdrill = CTinkerDrill()
	GameRules.tinkerdrill:Init()
end

-- call a GameRules/GameMode setter only if this Dota build has it, so one renamed API can't break the drill
local function try(obj, method, ...)
	if obj and obj[method] then
		local ok, err = pcall(obj[method], obj, ...)
		if not ok then print("[tinker_drill] " .. method .. " failed: " .. tostring(err)) end
	else
		print("[tinker_drill] missing API: " .. method)
	end
end

function CTinkerDrill:Init()
	local gm = GameRules:GetGameModeEntity()
	try(gm, "SetCustomGameForceHero", "npc_dota_hero_tinker")
	try(GameRules, "SetCustomGameTeamMaxPlayers", DOTA_TEAM_GOODGUYS, 1)
	try(GameRules, "SetCustomGameTeamMaxPlayers", DOTA_TEAM_BADGUYS, 0)
	try(GameRules, "SetCustomGameSetupTimeout", 0)
	try(GameRules, "SetCustomGameSetupAutoLaunchDelay", 0)
	try(GameRules, "SetHeroSelectionTime", 0)
	try(GameRules, "SetStrategyTime", 0)
	try(GameRules, "SetShowcaseTime", 0)
	try(GameRules, "SetPreGameTime", 0)
	try(GameRules, "SetPostGameTime", 20)
	try(gm, "SetFixedRespawnTime", 5)
	SendToServerConsole("sv_cheats 1")
	self.phase = "wait"
	self.hero = nil
	self.applied = false
	ListenToGameEvent("npc_spawned", Dynamic_Wrap(CTinkerDrill, "OnNPCSpawned"), self)
	gm:SetContextThink("TinkerDrillThink", function() return self:Think() end, 0)
	print("[tinker_drill] loaded state: " .. tostring(STATE.source))
end

function CTinkerDrill:OnNPCSpawned(event)
	local unit = EntIndexToHScript(event.entindex)
	if unit and unit:IsRealHero() and self.hero == nil then
		self.hero = unit
	end
end

function CTinkerDrill:ApplyState()
	local h = self.hero
	for _ = h:GetLevel(), STATE.level - 1 do
		h:HeroLevelUp(false)
	end
	for name, lvl in pairs(STATE.abilities) do
		local ab = h:FindAbilityByName(name)
		if ab then ab:SetLevel(lvl) end
	end
	h:SetAbilityPoints(0)
	for slot = 0, 16 do
		local it = h:GetItemInSlot(slot)
		if it then h:RemoveItem(it) end
	end
	for _, name in ipairs(STATE.items) do
		h:AddItemByName(name)
	end
	PlayerResource:SetGold(h:GetPlayerID(), STATE.gold, false)
	-- held safely in fountain while the clock runs to 5:00
	h:AddNewModifier(h, nil, "modifier_stunned", {})
	h:AddNewModifier(h, nil, "modifier_invulnerable", {})
	self.applied = true
	GameRules:SendCustomMessage("Tinker drill: saved state loaded (" .. tostring(STATE.source) .. "). Fast-forwarding to 5:00...", 0, 0)
end

function CTinkerDrill:Go()
	local h = self.hero
	SendToServerConsole("host_timescale 1")
	h:RemoveModifierByName("modifier_stunned")
	h:RemoveModifierByName("modifier_invulnerable")
	h:SetHealth(h:GetMaxHealth())
	h:SetMana(h:GetMaxMana())
	for i = 0, h:GetAbilityCount() - 1 do
		local ab = h:GetAbilityByIndex(i)
		if ab then ab:EndCooldown() end
	end
	-- passive gold earned while fast-forwarding doesn't count: back to the saved amount
	PlayerResource:SetGold(h:GetPlayerID(), STATE.gold, false)
	GameRules:SendCustomMessage("5:00 - GO! Keen -> fountain -> camp A. The drill ends at 10:00.", 0, 0)
end

function CTinkerDrill:Think()
	local state = GameRules:State_Get()
	if self.hero and not self.applied then
		self:ApplyState()
	end
	if state ~= DOTA_GAMERULES_STATE_GAME_IN_PROGRESS then
		return 0.25
	end
	local t = GameRules:GetDOTATime(false, false)
	if self.phase == "wait" and self.applied then
		SendToServerConsole("host_timescale " .. STATE.speed)
		self.phase = "ffwd"
	elseif self.phase == "ffwd" and t >= STATE.start_at - 5 then
		self:Go()
		self.phase = "play"
	elseif self.phase == "play" and t >= STATE.end_at then
		self.phase = "done"
		GameRules:SendCustomMessage("10:00 - drill over. Your run is on the coach's score sheet.", 0, 0)
		GameRules:SetGameWinner(DOTA_TEAM_GOODGUYS)
	end
	return 0.1
end
'''


def lua_state(st: dict) -> str:
    ab = ", ".join(f'{k} = {int(v)}' for k, v in st["abilities"].items())
    items = ", ".join(f'"{i}"' for i in st["items"])
    return (f'-- Saved drill state (written by tinker_coach/workshop.py)\nreturn {{\n'
            f'\tsource = "{st["source"]}",\n\tlevel = {int(st["level"])},\n\tabilities = {{ {ab} }},\n'
            f'\titems = {{ {items} }},\n\tgold = {int(st["gold"])},\n\tstart_at = 300,\n\tend_at = 600,\n\tspeed = 10,\n}}\n')


def install(state: dict | None = None):
    (GAME_DIR / "scripts" / "vscripts").mkdir(parents=True, exist_ok=True)
    CONTENT_DIR.mkdir(parents=True, exist_ok=True)           # the tools only list addons that have a content folder
    (GAME_DIR / "addoninfo.txt").write_text(ADDONINFO, encoding="utf-8")
    (GAME_DIR / "scripts" / "vscripts" / "addon_game_mode.lua").write_text(LUA, encoding="utf-8")
    st_file = GAME_DIR / "scripts" / "vscripts" / "drill_state.lua"
    if state or not st_file.exists():
        st_file.write_text(lua_state(state or DEFAULT_STATE), encoding="utf-8")
    return GAME_DIR


def state_from_session(path: str | None = None, at: int = 300) -> dict | None:
    """Your level, skills, items and gold at ~5:00 from a coach session (first update at/after `at`)."""
    files = [path] if path else sorted(glob.glob(str(HERE / "sessions" / "*.jsonl")), key=os.path.getmtime, reverse=True)
    for f in files:
        for line in open(f, encoding="utf-8"):
            p = json.loads(line)["p"]
            c = (p.get("map") or {}).get("clock_time")
            h = p.get("hero") or {}
            if h.get("name") != "npc_dota_hero_tinker" or c is None or c < at:
                continue
            if c > at + 20 or int(h.get("level", 0)) < 5:
                break                                         # this session doesn't have a usable 5:00 state
            abil = {a["name"]: int(a.get("level", 0)) for a in (p.get("abilities") or {}).values()
                    if isinstance(a, dict) and a.get("name", "").startswith("tinker_") and a.get("level")}
            items = [v["name"] for k, v in sorted((p.get("items") or {}).items())
                     if isinstance(v, dict) and v.get("name", "empty") != "empty" and not k.startswith("neutral")]
            return {"source": f"{pathlib.Path(f).stem} at {int(c) // 60}:{int(c) % 60:02d}", "level": int(h["level"]),
                    "abilities": abil, "items": items, "gold": int((p.get("player") or {}).get("gold", 0))}
    return None


def target_nw5() -> int:
    """Your own average net worth at 5:00 in real (non-drill) runs; Immortal median if there are none."""
    import csv
    vals = []
    runs = HERE / "runs.csv"
    if runs.exists():
        for r in csv.DictReader(open(runs, encoding="utf-8")):
            if r["match"] in SAMPLE_MATCHES:                                        # simulator test data, not you
                continue
            if r["minute"] == "5" and r["net_worth"] and int(r["lh"] or 0) >= 15:     # real laning, not a drill
                vals.append(int(r["net_worth"]))
    return round(sum(vals) / len(vals)) if vals else json.loads((HERE / "coach_data.json").read_text())["bench_nw"]["immortal_median"][5]


def fit_gold(st: dict) -> dict:
    """Set gold so items + gold = your real 5:00 net worth."""
    costs = json.loads((HERE / "item_costs.json").read_text(encoding="utf-8")) if (HERE / "item_costs.json").exists() else {}
    items_value = sum(costs.get(n, 0) for n in st["items"])
    st = dict(st, gold=max(0, target_nw5() - items_value))
    st["source"] += f", net worth {items_value + st['gold']:,} at 5:00"
    return st


def _unused():
    return None


def play():
    args = [str(STEAM / "steam.exe"), "-applaunch", "570", "-tools", "-addon", ADDON, "-novid", "-gamestateintegration", "-language", "english",
            "+dota_launch_custom_game", ADDON, "dota"]
    subprocess.Popen(args)
    return args


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "play"
    if cmd == "install":
        print("Addon written to", install())
    elif cmd == "save":
        st = state_from_session(sys.argv[2] if len(sys.argv) > 2 else None)
        if not st:
            print("No recorded session with a clean 5:00 snapshot yet; using the default state.")
            st = DEFAULT_STATE
        st = fit_gold(st)
        install(st)
        print("Saved drill state:", json.dumps(st))
    elif cmd == "play":
        install()
        print("Launching:", " ".join(play()[1:]))
