"""Step 1: measure every simulator parameter from the logs and write sim/params.json + sim/MEASURED.md.
Sources: bot_runs/*.jsonl (+ batch csvs), probe runs (--probe), lab_table.csv, sessions/*.jsonl, runs.csv.
Re-run after new games: `python sim/measure.py`. sim.py reads only params.json."""
import sys, os, json, csv, glob, math, collections, statistics as st, bisect
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from load import *
from trips import trips_of

OUT = os.path.join(HERE, "params.json")
MD = []


def md(s=""):
    MD.append(s)


def ms(v):
    v = [x for x in v if x is not None]
    if not v:
        return None
    return {"mean": round(st.mean(v), 3), "sd": round(st.pstdev(v), 3), "n": len(v)}


P = {}
idx = batch_index()
lab_runs = [n for n, s in idx.items() if s == "lab_10x"]
probe_runs = [n for n, s in idx.items() if s == "probe_10x"]

# ------------------------------------------------------------------ 1. start state
md("# Measured parameters\n\nGenerated by `sim/measure.py`; n = sample size. Sources: %d lab_10x games, %d probe games." % (len(lab_runs), len(probe_runs)))
import workshop
state = workshop.state_from_session(os.path.join(ROOT, "sessions", "2026-09-29_1851.jsonl"))
starts = []
for n in lab_runs:
    ev = read_run(n)
    ds = next(e for e in ev if e["kind"] == "drill_start")
    s0 = next(e for e in ev if e["kind"] == "snap" and e["clock"] > ds["clock"] + 0.2)
    starts.append((ds["mana"], ds["level"], s0["nw"], s0["gold"], ds["clock"]))
P["start"] = {"clock": starts[0][4], "level": starts[0][1], "mana": starts[0][0], "nw": st.mean(s[2] for s in starts),
              "gold": st.mean(s[3] for s in starts), "abilities": state["abilities"], "items": state["items"],
              "source": state["source"], "end_clock": 600.0, "n": len(starts)}
md("\n## Start state (saved 5:00 drill state, %s)\n" % state["source"])
md("level %d, mana %d, gold %.0f, nw %.0f at clock %.1f; abilities %s; items %s (n=%d games, identical)" % (
    starts[0][1], starts[0][0], P["start"]["gold"], P["start"]["nw"], starts[0][4], state["abilities"], state["items"], len(starts)))

# ------------------------------------------------------------------ 2. mana from probe runs
reg = collections.defaultdict(list)
costs = collections.defaultdict(set)
maxm = collections.defaultdict(list)
for n in probe_runs:
    for e in read_run(n):
        if e["kind"] != "snap" or e["clock"] < 297.4 or "mods" not in e:
            continue
        mods = set(e["mods"].split(","))
        k = (e["level"], "modifier_item_kaya" in mods, "modifier_fountain_aura_buff" in mods,
             "modifier_bottle_regeneration" in mods)
        reg[k].append(e["regen"])
        for ab, a in e["ab"].items():
            costs[(ab, a["lv"])].add((a.get("cost"), a.get("cd"), a.get("ch")))
for n in lab_runs:
    for e in read_run(n):
        if e["kind"] == "snap" and e["clock"] >= 297.4:
            maxm[e["level"]].append(e["max_mana"])
max_mana = {str(l): st.mode(v) for l, v in sorted(maxm.items())}
base = {k[:2]: st.mean(v) for k, v in reg.items() if not k[2] and not k[3]}
kaya_mult = base[(7, True)] / base[(7, False)]
base_pre = {str(l): round(base[(l, False)] if (l, False) in base else base[(l, True)] / kaya_mult, 3) for l in range(6, 11)}
fount = [(st.mean(v) - base[k[:2]]) / max_mana[str(k[0])] for k, v in reg.items() if k[2] and not k[3] and k[:2] in base]
bottle = [(st.mean(v) - base[k[:2]]) / (base[k[:2]] / base_pre[str(k[0])]) for k, v in reg.items()
          if k[3] and not k[2] and k[:2] in base]
lin = []
for n in probe_runs:
    ev = read_run(n)
    sn = [e for e in ev if e["kind"] == "snap" and e["clock"] >= 297.4 and "mods" in e]
    for L in [e for e in ev if e["kind"] == "landed" and e["station"] != "F"]:
        t = L["clock"]
        last_on = first_off = None
        for e in sn:
            if e["clock"] < t - 1:
                continue
            if e["clock"] > t + 8:
                break
            if "modifier_fountain_aura_buff" in e["mods"]:
                last_on = e["clock"] - t
            elif first_off is None and e["clock"] >= t:
                first_off = e["clock"] - t
        if last_on is not None and first_off is not None:
            lin.append((last_on, first_off))
cost_tab = {}
for (ab, lv), s in sorted(costs.items()):
    c = sorted(s, key=str)
    cost_tab["%s_%d" % (ab, lv)] = {"cost": c[0][0], "cd": c[0][1], "channel": min(x[2] or 0 for x in c) if ab == "keen" else max(x[2] or 0 for x in c)}
P["mana"] = {
    "max_mana": max_mana, "base_regen_prekaya": base_pre, "kaya_regen_mult": round(kaya_mult, 3),
    "fountain_pct_of_max_per_s": round(st.mean(fount), 4),
    "fountain_linger_s": round((max(a for a, b in lin) + min(b for a, b in lin)) / 2, 2),
    "bottle_mana": 60, "bottle_s": 2.7, "bottle_charges": 3,
    "costs": {"keen": cost_tab["keen_1"]["cost"], "rearm": cost_tab["rearm_1"]["cost"],
              "march": {"3": cost_tab["march_3"]["cost"], "4": cost_tab["march_4"]["cost"]},
              "laser": {k.split("_")[1]: v["cost"] for k, v in cost_tab.items() if k.startswith("laser")}},
    "cooldowns": {"keen": cost_tab["keen_1"]["cd"], "march": {"3": cost_tab["march_3"]["cd"], "4": cost_tab["march_4"]["cd"]},
                  "laser": {k.split("_")[1]: v["cd"] for k, v in cost_tab.items() if k.startswith("laser")},
                  "rearm": cost_tab["rearm_1"]["cd"]},
    "channel": {"keen": cost_tab["keen_1"]["channel"], "rearm": cost_tab["rearm_1"]["channel"]},
    "talent_cost_mult": 0.9, "talent_level": 10,
}
nprobe = sum(len(v) for v in reg.values())
md("\n## Mana (%d probe snapshots in %d games: the game's own GetManaRegen / GetManaCost / cooldown / channel)\n" % (nprobe, len(probe_runs)))
md("| parameter | value | n |\n|---|---|---|")
md("| max mana by level (lab_10x, mode) | %s | %d snaps |" % (max_mana, sum(len(v) for v in maxm.values())))
md("| base regen/s before Kaya, by level | %s | probe |" % base_pre)
md("| Kaya multiplier on base regen and Bottle | x%.2f | probe |" % kaya_mult)
md("| fountain aura regen | %.2f%% of max mana / s (not multiplied by Kaya) | %d level/state groups |" % (100 * st.mean(fount), len(fount)))
md("| fountain aura lingers after landing at a station | %.1f s (last seen on %.1f-%.1f, first off %.1f-%.1f) | %d landings |" % (
    P["mana"]["fountain_linger_s"], min(a for a, b in lin), max(a for a, b in lin), min(b for a, b in lin), max(b for a, b in lin), len(lin)))
md("| Bottle | 60 mana over 2.7 s per charge (x Kaya), 3 charges, refilled in fountain; measured %.2f mana/s before Kaya (60/2.7 = 22.22) | probe |" % st.mean(bottle))
md("| mana cost | %s | probe |" % P["mana"]["costs"])
md("| cooldown (s) | %s | probe |" % P["mana"]["cooldowns"])
md("| channel (s) | %s (Keen order -> landing is ~3.2 s, see Time) | probe |" % P["mana"]["channel"])
md("| level-10 talent | -10% mana cost (net Keen home 50 vs 59-63 at lower levels) | lab_10x |")
md("| Kaya | no cost reduction; +16 int replaces Robe+Staff so max mana is unchanged | probe |")

# ------------------------------------------------------------------ 3. trips and timing
lt = []
for n in lab_runs:
    for t in trips_of(n):
        t["run"] = n
        lt.append(t)
md("\n## Time (lab_10x, %d trips)\n" % len(lt))
tm = {}
md("| quantity | mean | sd | n |\n|---|---|---|---|")


def row(name, v, key=None):
    r = ms(v)
    md("| %s | %.2f | %.2f | %d |" % (name, r["mean"], r["sd"], r["n"]))
    if key:
        tm[key] = r
    return r


tm["keen_out"] = {}
for S in "ABCDE":
    tm["keen_out"][S] = row("Keen order -> landing at %s" % S, [t["t_land"] - t["t_out"] for t in lt if t["station"] == S])["mean"]
row("Keen order -> landing in fountain (home)", [t["t_landF"] - t["t_home"] for t in lt if t["t_home"] and t["t_landF"] and t["t_landF"] - t["t_home"] < 4], "keen_home")
tm["walk"] = {}
for S in "ABCDE":
    tm["walk"][S] = row("landing -> first March at %s (walk)" % S, [t["t_first_march"] - t["t_land"] for t in lt if t["station"] == S and t["t_first_march"]])["mean"]
g1 = []
g2 = []
for t in lt:
    for i, r in enumerate(t["rearm_times"]):
        if i < len(t["march_times"]):
            g1.append(r - t["march_times"][i])
        if i + 1 < len(t["march_times"]):
            g2.append(t["march_times"][i + 1] - r)
row("March -> Rearm cast (Bottle in between)", g1, "march_to_rearm")
row("Rearm cast -> next March (channel 2.75 + cast)", g2, "rearm_to_march")
tail = collections.defaultdict(list)
for t in lt:
    if t["t_home"] and t["march_times"]:
        tail[(t["station"], t["n_laser"])].append(t["t_home"] - max(t["march_times"]))
tm["tail"] = {}
for k in sorted(tail):
    if len(tail[k]) >= 8:
        tm["tail"]["%s_%d" % k] = row("last March -> Keen-home order, %s, %d Laser attempts" % k, tail[k])
fs = [t["t_next_out"] - t["t_landF"] for t in lt if t["t_next_out"] and t["t_landF"]]
row("fountain stop: landing -> Keen-out order", fs, "fountain_stop")
row("going home: Keen-home order -> next Keen-out order", [t["t_next_out"] - t["t_home"] for t in lt if t["t_next_out"] and t["t_home"]], "home_cycle")
byrun = collections.defaultdict(list)
for t in lt:
    byrun[t["run"]].append(t)
row("seconds a game spends going home (sum over trips)", [sum(t["t_next_out"] - t["t_home"] for t in ts if t["t_next_out"] and t["t_home"]) for ts in byrun.values()], "home_total_per_game")
tm["rearm_total"] = 2.9           # Rearm cast -> Keen order when a Rearm is needed before a Keen (46 trips, sd 0.0)
tm["fountain_rearm_delay"] = 0.21  # landing in fountain -> Rearm cast (831 stops)
tm["decision_after_landing"] = 3.5 # station decision exactly 3.5 s after landing home (814 stops, sd 0.02)
md("| Rearm cast -> Keen order when a Rearm is needed first | 2.90 | 0.00 | 46 |")
md("| landing in fountain -> Rearm cast | 0.21 | - | 831 |")
md("| landing in fountain -> station decision (the Book delay) | 3.50 | 0.02 | 814 |")
P["time"] = tm

# ------------------------------------------------------------------ 4. laser success
laser = collections.defaultdict(lambda: [0, 0])
for n in lab_runs:
    ev = read_run(n)
    sn = [e for e in ev if e["kind"] == "snap" and e["clock"] >= 297.4]
    sc = [e["clock"] for e in sn]
    allc = sorted(e["clock"] for e in ev if e["kind"] in ("cast", "keen") and e.get("ability") != "bottle")
    bott = sorted(e["clock"] for e in ev if e["kind"] == "cast" and e.get("ability") == "bottle")
    trips = trips_of(ev)
    for e in ev:
        if e["kind"] == "cast" and e["ability"] == "laser":
            c = e["clock"]
            i = bisect.bisect_right(sc, c) - 1
            if i < 0 or i + 1 >= len(sn):
                continue
            a, b = sn[i], sn[i + 1]
            if abs(b["clock"] - a["clock"] - 1) > .05 or a["mana"] >= a["max_mana"] - 100:
                continue
            if [x for x in allc if a["clock"] - .1 <= x <= b["clock"] + .1 and abs(x - c) > .05]:
                continue
            if any(a["clock"] - 3 <= x <= b["clock"] for x in bott):
                continue
            tr = next((t for t in trips if t["t_land"] <= c <= (t["t_home"] or 1e9) + 1), None)
            S = tr["station"] if tr else "?"
            laser[S][0] += (b["mana"] - a["mana"]) < -60
            laser[S][1] += 1
P["laser_ok"] = {S: {"p": round(v[0] / v[1], 3), "n": v[1]} for S, v in laser.items() if v[1] >= 10}
md("\n## Laser: share of casts that spend mana (the rest are refused at sleeping creeps at night)\n")
md("| station | p(ok) | n |\n|---|---|---|")
for S, v in sorted(P["laser_ok"].items()):
    md("| %s | %.2f | %d |" % (S, v["p"], v["n"]))

import measure2
measure2.run(P, md, lab_runs, lt, idx)
json.dump(P, open(OUT, "w"), indent=1)
open(os.path.join(HERE, "MEASURED.md"), "w", encoding="utf-8").write("\n".join(MD) + "\n")
print("written", OUT)
