-- Tinker Jev bot: plays Tinker from 0:00 on the normal map (no enemy heroes).
-- Generated by tinker_coach/bot.py. Settings (and the Immortal-derived stations) live in bot_config.lua.
--
-- How it plays (from 44 Immortal replays, patch 7.41):
--   lane:     last hits by arithmetic, Laser the ranged creep, shove with March from 4:15, Keen home at level 6
--   fountain: Bottle, Rearm, Bottle, Keen  (Immortal median stop 7.5 s)
--   station:  Keen to the Immortal landing spot, walk to the Immortal March spot, March facing the Immortal
--             direction, Bottle, Rearm, March turned 180, Bottle, Rearm, March, then Keen away at once:
--             the robots finish the camp during the 3 s channel (their kills still count)
--   decisions (where next, how to finish) go to the local bridge (bot_bridge in bot.py), which asks Jev;
--   no answer in time -> the built-in rule. Everything is logged. Type -bot in chat to take over.

local CFG = require("bot_config")

if TinkerBot == nil then _G.TinkerBot = class({}) end

function Precache(context)
	PrecacheUnitByNameSync("npc_dota_hero_tinker", context)
end

function Activate()
	GameRules.tinkerbot = TinkerBot()
	GameRules.tinkerbot:Init()
end

-- ------------------------------------------------------------------ helpers
local function enc(v)
	local t = type(v)
	if t == "nil" then return "null"
	elseif t == "boolean" then return v and "true" or "false"
	elseif t == "number" then
		if v ~= v or v == math.huge or v == -math.huge then return "null" end
		if math.floor(v) == v then return string.format("%d", v) end
		return string.format("%.3f", v)
	elseif t == "string" then
		return '"' .. v:gsub('\\', '\\\\'):gsub('"', '\\"'):gsub('\n', '\\n') .. '"'
	elseif t == "table" then
		if #v > 0 or next(v) == nil then
			local out = {}
			for i = 1, #v do out[i] = enc(v[i]) end
			return "[" .. table.concat(out, ",") .. "]"
		end
		local out = {}
		for k, val in pairs(v) do table.insert(out, enc(tostring(k)) .. ":" .. enc(val)) end
		return "{" .. table.concat(out, ",") .. "}"
	end
	return '"' .. tostring(v) .. '"'
end

local function vec(p) return Vector(p[1], p[2], 0) end
local function dist2(a, b) return ((a.x - b.x) ^ 2 + (a.y - b.y) ^ 2) ^ 0.5 end
local function clockstr(t)
	local s = t < 0 and "-" or ""
	t = math.floor(math.abs(t))
	return string.format("%s%d:%02d", s, math.floor(t / 60), t % 60)
end
local function yawdir(deg) local a = math.rad(deg); return Vector(math.cos(a), math.sin(a), 0) end
local function contains(list, x) for _, v in ipairs(list) do if v == x then return true end end return false end

local function try(obj, method, ...)
	if obj and obj[method] then
		local ok, err = pcall(obj[method], obj, ...)
		if not ok then print("[tinker_bot] " .. method .. " failed: " .. tostring(err)) end
	else
		print("[tinker_bot] missing API: " .. method)
	end
end

-- ------------------------------------------------------------------ setup
function TinkerBot:Init()
	local gm = GameRules:GetGameModeEntity()
	try(gm, "SetCustomGameForceHero", "npc_dota_hero_tinker")
	try(GameRules, "SetCustomGameTeamMaxPlayers", DOTA_TEAM_GOODGUYS, 1)
	try(GameRules, "SetCustomGameTeamMaxPlayers", DOTA_TEAM_BADGUYS, 0)
	try(GameRules, "SetCustomGameSetupTimeout", 4)
	try(GameRules, "SetCustomGameSetupAutoLaunchDelay", 4)
	try(GameRules, "LockCustomGameSetupTeamAssignment", true)
	try(GameRules, "SetHeroSelectPenaltyTime", 0)
	try(GameRules, "SetHeroSelectionTime", 0)
	try(GameRules, "SetStrategyTime", 0)
	try(GameRules, "SetShowcaseTime", 0)
	try(GameRules, "SetPreGameTime", CFG.pregame)
	try(GameRules, "SetPostGameTime", 30)
	-- normal Dota passive gold (custom games default to none; your F11 lobby had it): 1 gold every 0.6 s
	try(GameRules, "SetGoldPerTick", 1)
	try(GameRules, "SetGoldTickTime", 0.6)
	SendToServerConsole("sv_cheats 1")
	self.hero = nil
	self.enabled = true
	self.phase = "wait"
	self.buy_i = 1
	self.last_cleared = {}
	self.trips = {}
	self.pending = nil
	self.next_log = 0
	self.speed = 1
	self.phase_since = 0
	self.bg = {}          -- background decisions in flight
	self.bookings = {}    -- camps to check a few seconds after leaving (robots keep working)
	ListenToGameEvent("npc_spawned", Dynamic_Wrap(TinkerBot, "OnNPCSpawned"), self)
	ListenToGameEvent("game_rules_state_change", Dynamic_Wrap(TinkerBot, "OnState"), self)
	ListenToGameEvent("player_chat", Dynamic_Wrap(TinkerBot, "OnChat"), self)
	gm:SetContextThink("TinkerBotThink", function() return self:Think() end, 0)
	print("[tinker_bot] loaded; advisor = " .. CFG.advisor)
	self:Log("hello", {advisor = CFG.advisor})
end

function TinkerBot:AssignPlayers()
	for pid = 0, 23 do
		if PlayerResource:IsValidPlayerID(pid) then
			pcall(function() PlayerResource:SetCustomTeamAssignment(pid, DOTA_TEAM_GOODGUYS) end)
		end
	end
end

function TinkerBot:OnState()
	local st = GameRules:State_Get()
	self:Log("state", {state = st})
	if st == DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP then self:AssignPlayers() end
end

-- if no hero exists once the game is past hero selection (player joined late, pick skipped), make one
function TinkerBot:EnsureHero()
	if self.hero or GameRules:State_Get() < DOTA_GAMERULES_STATE_PRE_GAME then return end
	for pid = 0, 23 do
		if PlayerResource:IsValidPlayerID(pid) then
			local existing = PlayerResource:GetSelectedHeroEntity(pid)
			if existing then return self:Adopt(existing, "your hero") end
		end
	end
	-- the game normally spawns your forced Tinker a moment into pre-game; only if it hasn't after 6 s, make one
	self.pregame_at = self.pregame_at or GameRules:GetGameTime()
	if GameRules:GetGameTime() - self.pregame_at < 6 then return end
	for pid = 0, 23 do
		local pl = PlayerResource:IsValidPlayerID(pid) and PlayerResource:GetPlayer(pid) or nil
		if pl then
			if pl:GetTeam() ~= DOTA_TEAM_GOODGUYS then pl:SetTeam(DOTA_TEAM_GOODGUYS) end
			local h = CreateHeroForPlayer("npc_dota_hero_tinker", pl)
			if h then
				FindClearSpaceForUnit(h, self:FountainPos(), true)
				self:Log("hero_created", {pid = pid})
				return self:Adopt(h, "created")
			end
			return
		end
	end
end

function TinkerBot:FountainPos()
	if self.fountain then return self.fountain end
	for _, f in ipairs(Entities:FindAllByClassname("ent_dota_fountain")) do
		if f:GetTeamNumber() == DOTA_TEAM_GOODGUYS then
			self.fountain = f:GetAbsOrigin()
			return self.fountain
		end
	end
	self.fountain = vec(CFG.fountain)
	return self.fountain
end

function TinkerBot:Adopt(unit, how)
	self.hero = unit
	self.pid = unit:GetPlayerOwnerID()
	self:FountainPos()
	local p = unit:GetAbsOrigin()
	self:Log("spawn", {x = math.floor(p.x), y = math.floor(p.y), how = how,
		fountain_x = math.floor(self.fountain.x), fountain_y = math.floor(self.fountain.y)})
end

function TinkerBot:OnNPCSpawned(event)
	local unit = EntIndexToHScript(event.entindex)
	if unit and unit:IsRealHero() and self.hero == nil and unit:GetPlayerOwnerID() >= 0 then
		self:Adopt(unit, "spawned")
	end
end

function TinkerBot:OnChat(event)
	if event.text == "-bot" then
		self.enabled = not self.enabled
		GameRules:SendCustomMessage(self.enabled and "Bot: playing" or "Bot: paused, you have control", 0, 0)
		self:Log("toggle", {enabled = self.enabled})
		if self.enabled then self:SetPhase("go_home") end
	end
end

function TinkerBot:SetSpeed(s)
	if s ~= self.speed then
		self.speed = s
		SendToServerConsole("host_timescale " .. s)
		self:Log("speed", {x = s})
	end
end

function TinkerBot:SetPhase(p)
	self.phase = p
	self.phase_since = GameRules:GetGameTime()
end

-- ------------------------------------------------------------------ bridge
function TinkerBot:Post(path, body, cb)
	local req = CreateHTTPRequestScriptVM("POST", CFG.bridge .. path)
	if not req then return end
	req:SetHTTPRequestRawPostBody("application/json", enc(body))
	req:Send(function(res)
		if cb then cb(res and res.StatusCode == 200 and res.Body or nil) end
	end)
end

function TinkerBot:Log(kind, data)
	data = data or {}
	data.kind = kind
	data.clock = GameRules:GetDOTATime(false, true)
	self:Post("/log", data)
end

-- Ask for a decision. rules = the built-in answer; options = the legal answers.
function TinkerBot:Decide(kind, state, options, rules, on_answer, background)
	if CFG.advisor == "rules" or #options <= 1 then
		self:Post("/decide", {kind = kind, state = state, options = options, rules = rules, rules_only = true})
		on_answer(rules, "rules")
		return
	end
	local ticket = {done = false}
	if background then table.insert(self.bg, ticket) else self.pending = ticket end
	local function finish(pick, src)
		if ticket.done then return end
		ticket.done = true
		if self.pending == ticket then self.pending = nil end
		if not contains(options, pick) then pick, src = rules, "rules" end
		on_answer(pick, src)
	end
	ticket.deadline = GameRules:GetGameTime() + CFG.decide_timeout * self.speed   -- real seconds -> game seconds
	ticket.fallback = function() finish(rules, "timeout") end
	self:Post("/decide", {kind = kind, state = state, options = options, rules = rules}, function(body)
		if not body then return finish(rules, "rules") end
		finish(body:match("pick=([%w_]+)") or rules, body:match("src=([%w_]+)") or "jev")
	end)
end

-- ------------------------------------------------------------------ facts
function TinkerBot:Ab(name) return self.hero:FindAbilityByName(name) end

function TinkerBot:Ready(ab)
	return ab ~= nil and ab:GetLevel() > 0 and ab:IsCooldownReady() and self.hero:GetMana() >= ab:GetManaCost(-1)
end

function TinkerBot:Busy()
	local h = self.hero
	return h:IsChanneling() or (h:GetCurrentActiveAbility() ~= nil)
end

function TinkerBot:Clock() return GameRules:GetDOTATime(false, true) end
function TinkerBot:Minute() return math.floor(self:Clock() / 60) end
function TinkerBot:InFountain() return dist2(self.hero:GetAbsOrigin(), self.fountain) < 1300 end

function TinkerBot:Units(pos, radius, neutral)
	if neutral then
		local out = {}
		for _, u in ipairs(Entities:FindAllByClassnameWithin("npc_dota_creep_neutral", pos, radius)) do
			if u:IsAlive() and u:GetTeamNumber() == DOTA_TEAM_NEUTRALS then table.insert(out, u) end
		end
		return out
	end
	local found = FindUnitsInRadius(DOTA_TEAM_GOODGUYS, pos, nil, radius, DOTA_UNIT_TARGET_TEAM_ENEMY,
		DOTA_UNIT_TARGET_BASIC, DOTA_UNIT_TARGET_FLAG_NONE, FIND_CLOSEST, false)
	local out = {}
	for _, u in ipairs(found) do
		local team = u:GetTeamNumber()
		local ok = neutral and team == DOTA_TEAM_NEUTRALS or (not neutral and team == DOTA_TEAM_BADGUYS)
		if ok and u:IsAlive() and not u:IsBuilding() and not u:IsCourier() then table.insert(out, u) end
	end
	return out
end

function TinkerBot:MidWave()
	-- enemy lane creeps in the mid lane on our half of the map (our creeps and tower see them)
	local pts = {}
	for _, u in ipairs(self:Units(Vector(-1100, -1100, 0), 3000, false)) do
		local p = u:GetAbsOrigin()
		if math.abs(p.x - p.y) < 1800 and p.x + p.y < 1500 then table.insert(pts, p) end
	end
	if #pts < 3 then return nil end
	local cx, cy = 0, 0
	for _, p in ipairs(pts) do cx = cx + p.x; cy = cy + p.y end
	local c = Vector(cx / #pts, cy / #pts, 0)
	if dist2(c, vec(CFG.stations.B.land)) > 1400 then return nil end               -- out of reach of the Keen
	local f = self.fountain
	local threat = dist2(c, f) < dist2(vec(CFG.t1_mid), f) - 500 or dist2(c, vec(CFG.t2_mid)) < 1500
	return {n = #pts, pos = c, threat = threat}
end

-- every camp is remembered on its own: creeps last seen, refilled at :00 only if it was empty
-- (creeps left in a camp block its spawn), assumed full (4) when unseen since a respawn
function TinkerBot:UpdateCamps(now)
	if not self.camps then
		self.camps = {}
		-- the replay camp spots are where the Marches landed, not always where a camp is: pair each with a neutral
		-- spawner, closest pairs first, and drop spots with none (bot runs 2026-09-30: A's 2nd and D's 3rd spot have
		-- no camp of their own and read 0 creeps every time)
		local spawners, spots, pairs_ = Entities:FindAllByClassname("npc_dota_neutral_spawner"), {}, {}
		for st, S in pairs(CFG.stations) do
			for _, c in ipairs(S.camps) do
				local spot = {st = st, xy = c}
				table.insert(spots, spot)
				for _, sp in ipairs(spawners) do
					local d = dist2(vec(c), sp:GetAbsOrigin())
					if d < 900 then table.insert(pairs_, {spot = spot, sp = sp, d = d}) end
				end
			end
		end
		table.sort(pairs_, function(a, b) return a.d < b.d end)
		local used = {}
		for _, pr in ipairs(pairs_) do
			if not pr.spot.sp and not used[pr.sp] then pr.spot.sp, pr.spot.d, used[pr.sp] = pr.sp, pr.d, true end
		end
		for _, spot in ipairs(spots) do
			local pos = spot.sp and spot.sp:GetAbsOrigin() or vec(spot.xy)
			local keep = spot.sp ~= nil or #spawners == 0             -- no spawners found at all: keep the old spots
			self:Log("camp_spot", {station = spot.st, x = spot.xy[1], y = spot.xy[2], moved = spot.d and math.floor(spot.d),
				to_x = math.floor(pos.x), to_y = math.floor(pos.y), dropped = not keep or nil, spawners = #spawners})
			if keep then table.insert(self.camps, {st = spot.st, pos = pos, n = 4, seen = -1}) end
		end
		self.camp_minute = self:Minute()
	end
	local m = self:Minute()
	if m ~= self.camp_minute then
		-- leftovers block a camp's :00 spawn, so only an empty camp gets a new set
		-- (bot run 2026-09-30: camps left with creeps grew +0.7 per :00, not +4)
		for _, c in ipairs(self.camps) do if c.n == 0 then c.n = c.full or 4 end end
		self.camp_minute = m
	end
	if now < (self.next_camp_scan or 0) then return end
	self.next_camp_scan = now + 0.4
	local p = self.hero:GetAbsOrigin()
	for i, c in ipairs(self.camps) do
		if dist2(p, c.pos) < 1100 then
			local n = #self:Units(c.pos, 650, true)
			if now - c.seen > 5 then
				-- first look in a while: the guess vs what's really there, and whether leftovers blocked the :00 spawn
				self:Log("camp_seen", {station = c.st, camp = i, expected = c.n, actual = n, last_seen = c.seen_n,
					spawns = c.seen_minute and m - c.seen_minute, unseen_s = c.seen >= 0 and math.floor(now - c.seen) or nil})
			end
			c.n, c.seen, c.seen_n, c.seen_minute = n, now, n, m
			if not c.full and n > 0 then c.full = n end         -- first sight with creeps = one set (4-6 by camp)
		end
	end
end

function TinkerBot:StationValue(st)
	local v = 0
	for _, c in ipairs(self.camps or {}) do
		-- cleared, a new set (a straggler walking back is +1), or 90 s on: leftovers block the spawn, so without
		-- a timeout a stuck camp stayed dead all game (run 7: A and D stuck by 6:45, 30+ s idle in fountain)
		if c.stuck and (c.n == 0 or c.n >= c.stuck + 3 or GameRules:GetGameTime() - c.stuck_at > 90) then
			c.stuck, c.low = nil, 0
		end
		if c.st == st and not c.stuck then v = v + c.n end
	end
	return v
end

function TinkerBot:CampReady(st)
	if st == "B" then return true end
	-- (tried: counting only camps holding a full set, so 4+ leftovers don't look fresh. Run 9 was the worst
	-- Jev run, 4,278, and it missed A's 5 leftovers anyway since a set's size is learned from one look.)
	local v = self:StationValue(st)
	if v >= 4 then return true end
	-- low now but the :00 spawn lands before we would: count it as ready (we wait for it there);
	-- only camps that are empty get that spawn, leftovers block it
	if 60 - self:Clock() % 60 > 6 then return false end
	for _, c in ipairs(self.camps or {}) do if c.st == st and c.n == 0 then v = v + (c.full or 4) end end
	return v >= 4
end

-- a station holding only leftovers: they block its :00 spawn, so it stays this low until someone clears it;
-- worth a trip when nothing full is up (bot run 2026-09-30: A sat at 2 creeps from 5:17 to 10:00, and a 44 s
-- fountain wait with every camp blocked)
function TinkerBot:CleanupReady(st)
	if st == "B" then return false end
	local v = self:StationValue(st)
	return v >= 1 and not self:CampReady(st)
end

function TinkerBot:CampReadyOld(st)
	local lo = self.leftover and self.leftover[st]
	if lo and lo.minute == self:Minute() then return lo.n >= 3 end        -- stragglers block the respawn anyway
	local lc = self.last_cleared[st] or -1
	local soon = 60 - self:Clock() % 60 <= 10          -- respawns before a Keen would land
	return lc < self:Minute() or (soon and lc == self:Minute())
end

function TinkerBot:StationCreeps(st)
	-- living neutrals at the station's camps (used after leaving, to book the camp as cleared or not)
	local n = 0
	for _, c in ipairs(self.camps or {}) do if c.st == st then n = n + #self:Units(c.pos, 700, true) end end
	return n
end

function TinkerBot:BottleCharges()
	for slot = 0, 5 do
		local it = self.hero:GetItemInSlot(slot)
		if it and it:GetName() == "item_bottle" then return it:GetCurrentCharges(), it end
	end
	return 0, nil
end

function TinkerBot:Costs()
	local m = self:Ab("tinker_march_of_the_machines")
	local r = self:Ab("tinker_rearm")
	local k = self:Ab("tinker_keen_teleport")
	return m:GetManaCost(-1), (r:GetLevel() > 0 and r:GetManaCost(-1) or 100), (k:GetLevel() > 0 and k:GetManaCost(-1) or 75)
end

-- mana to keep for the trip home: the Keen plus a buffer that grows with max mana (Immortals arrive with ~226
-- at ~900 max; at level 6 with ~520 max a flat 180 would cost the third March)
function TinkerBot:Reserve()
	return 40                     -- the Keen home is counted separately; arriving at fountain nearly dry costs nothing
end

-- mana a station's plan needs from the fountain: its Marches and Rearms, the Keen home and the reserve
function TinkerBot:PlanNeed(st)
	local mc, rc, kc = self:Costs()
	local n = st == "B" and 2 or (st == "D" and 2 or 3)
	local charges = self:BottleCharges()
	return n * mc + (n - 1) * rc + kc + self:Reserve() - charges * 60
end

-- ------------------------------------------------------------------ orders
function TinkerBot:Order(t)
	t.UnitIndex = self.hero:entindex()
	ExecuteOrderFromTable(t)
end

function TinkerBot:Move(pos) self:Order({OrderType = DOTA_UNIT_ORDER_MOVE_TO_POSITION, Position = pos}) end
function TinkerBot:CastPos(ab, pos) self:Order({OrderType = DOTA_UNIT_ORDER_CAST_POSITION, AbilityIndex = ab:entindex(), Position = pos}) end
function TinkerBot:CastTarget(ab, u) self:Order({OrderType = DOTA_UNIT_ORDER_CAST_TARGET, AbilityIndex = ab:entindex(), TargetIndex = u:entindex()}) end
function TinkerBot:CastNo(ab) self:Order({OrderType = DOTA_UNIT_ORDER_CAST_NO_TARGET, AbilityIndex = ab:entindex()}) end
function TinkerBot:Attack(u) self:Order({OrderType = DOTA_UNIT_ORDER_ATTACK_TARGET, TargetIndex = u:entindex()}) end

-- the March direction that sweeps the most creep HP: robots walk a strip ~450 either side of the line, ~1500
-- long (estimate). Replaces the replay facings at camps: A's 325 pointed 77 deg off its only camp and the
-- 180 turns at A and D aimed at nothing once the camps were matched to real spawners (2026-09-30).
-- Each creep counts once, a tanky one (ancients, big creeps) a third: scoring by HP aimed the robots at C's
-- ancients, which they barely scratch (run 5: C +2 and +1 with 10-11 left).
-- A follow-up March (within 5 s) counts creeps still in the last March's path at 30%: its robots are still
-- walking there (run 5: every March at C went the same way; Immortals turn 180 onto the other camp).
function TinkerBot:BestMarchDir(p, targets)
	local ldmg = CFG.laser_dmg[self:Ab("tinker_laser"):GetLevel()] or 0
	local function inside(v, d)
		local along = v.x * d.x + v.y * d.y
		return along > -100 and along < 1500 and math.abs(v.x * d.y - v.y * d.x) < 450
	end
	local prev = self.last_march and GameRules:GetGameTime() - self.last_march < 5 and self.march_dir or nil
	local w, total = {}, 0
	for i, u in ipairs(targets) do
		w[i] = self:IsTanky(u, ldmg) and 0.33 or 1
		if prev and inside(u:GetAbsOrigin() - p, prev) then w[i] = w[i] * 0.3 end
		total = total + w[i]
	end
	local best, bs = nil, 0
	for k = 0, 35 do
		local d = yawdir(k * 10)
		local s = 0
		for i, u in ipairs(targets) do if inside(u:GetAbsOrigin() - p, d) then s = s + w[i] end end
		if s > bs then best, bs = d, s end
	end
	return best, total > 0 and bs / total or 0
end

-- where the Marches are aimed at the creeps instead of the replay facing: aiming won at C (5.5 kills a trip vs
-- 3.2-5.0) and held at D, but lost at A (1.5-2.0 vs ~4.4 with the Immortal facing) in runs on 2026-09-30
function TinkerBot:Aims(st)
	local s = CFG.aim_stations or {C = true, D = true, E = true}
	return s[st] == true
end

function TinkerBot:MarchDir(dir, why)
	local p = self.hero:GetAbsOrigin()
	self.march_dir = dir
	self:CastPos(self:Ab("tinker_march_of_the_machines"), p + dir * 250)
	self.last_march = GameRules:GetGameTime()
	local yaw = math.floor(math.deg(math.atan2(dir.y, dir.x)) % 360)
	self:Log("cast", {ability = "march", yaw = yaw, why = why, x = math.floor(p.x), y = math.floor(p.y)})
end

function TinkerBot:UseBottle(why)
	local h = self.hero
	local charges, it = self:BottleCharges()
	if not it or charges <= 0 or not it:IsCooldownReady() or h:HasModifier("modifier_bottle_regeneration") then return false end
	if h:GetMaxMana() - h:GetMana() < 60 and not self:InFountain() then return false end
	self:Order({OrderType = DOTA_UNIT_ORDER_CAST_NO_TARGET, AbilityIndex = it:entindex()})
	self:Log("cast", {ability = "bottle", why = why, charges = charges})
	return true
end

-- ------------------------------------------------------------------ skills and items
function TinkerBot:LevelUp()
	local h = self.hero
	local guard = 0
	while h:GetAbilityPoints() > 0 and guard < 4 do
		guard = guard + 1
		local order = {CFG.skill_order[h:GetLevel()] or "", "tinker_rearm", "tinker_march_of_the_machines", "tinker_laser",
			"tinker_deploy_turrets"}
		local done = false
		for _, name in ipairs(order) do
			local ab = name ~= "" and h:FindAbilityByName(name) or nil
			if ab and ab:GetLevel() < ab:GetMaxLevel() and ab:CanAbilityBeUpgraded() == ABILITY_CAN_BE_UPGRADED then
				h:UpgradeAbility(ab)
				self:Log("skill", {ability = name, level = ab:GetLevel(), hero_level = h:GetLevel()})
				done = true
				break
			end
		end
		if not done then break end
	end
end

function TinkerBot:Buy()
	local item = CFG.buy[self.buy_i]
	if not item then return end
	-- before the first Keen the courier brings items to lane; after it, buy only in fountain
	if self.keened and not self:InFountain() then return end
	if PlayerResource:GetGold(self.pid) < item.cost then return end
	local h = self.hero
	for _, comp in ipairs(item.consumes or {}) do
		for slot = 0, 16 do
			local it = h:GetItemInSlot(slot)
			if it and it:GetName() == comp then h:RemoveItem(it); break end
		end
	end
	PlayerResource:SpendGold(self.pid, item.cost, DOTA_ModifyGold_PurchaseItem)
	h:AddItemByName(item.name)
	self:Log("buy", {item = item.name, cost = item.cost, gold_left = PlayerResource:GetGold(self.pid)})
	self.buy_i = self.buy_i + 1
end

function TinkerBot:NetWorth()
	local ok, nw = pcall(function() return PlayerResource:GetNetWorth(self.pid) end)
	if ok and nw and nw > 0 then return nw end
	local total = PlayerResource:GetGold(self.pid)
	for slot = 0, 16 do
		local it = self.hero:GetItemInSlot(slot)
		if it then total = total + (it:GetCost() or 0) end
	end
	return total
end

-- ------------------------------------------------------------------ main loop
function TinkerBot:Think()
	if GameRules:State_Get() >= DOTA_GAMERULES_STATE_POST_GAME then return nil end
	if not self.hero then
		local ok, err = pcall(function() self:EnsureHero() end)
		if not ok then print("[tinker_bot] EnsureHero: " .. tostring(err)) end
		return 0.2
	end
	local h = self.hero
	local t = self:Clock()
	local now = GameRules:GetGameTime()
	if now >= self.next_log then
		self.next_log = now + 1
		local ok, err = pcall(function() self:Snapshot(t) end)
		if not ok then print("[tinker_bot] snapshot: " .. tostring(err)) end
	end
	if t >= CFG.end_at and not self.ended then
		self.ended = true
		pcall(function()
			self:Log("end", {lh = PlayerResource:GetLastHits(self.pid), nw = self:NetWorth(), gold = PlayerResource:GetGold(self.pid), level = h:GetLevel()})
		end)
		self:SetSpeed(1)
		GameRules:SendCustomMessage(clockstr(t) .. " - bot run over. Recording saved by the bridge.", 0, 0)
		GameRules:SetGameWinner(DOTA_TEAM_GOODGUYS)
		return nil
	end
	if t > 0 then
		self.gold_tick_at = self.gold_tick_at or now
		while now - self.gold_tick_at >= 0.7 do
			self.gold_tick_at = self.gold_tick_at + 0.7
			PlayerResource:ModifyGold(self.pid, 1, false, DOTA_ModifyGold_GameTick)
		end
	end
	if self.pending and self.pending.deadline and now > self.pending.deadline then self.pending.fallback() end
	for i = #self.bg, 1, -1 do
		local tk = self.bg[i]
		if tk.done then table.remove(self.bg, i) elseif tk.deadline and now > tk.deadline then tk.fallback(); table.remove(self.bg, i) end
	end
	for i = #self.bookings, 1, -1 do
		local b = self.bookings[i]
		if now >= b.at then
			table.remove(self.bookings, i)
			pcall(function() self:Book(b.trip) end)
		end
	end
	if not self.enabled or not h:IsAlive() then return 0.1 end
	local ok, err = pcall(function()
		self:UpdateCamps(now)
		if self.phase ~= "drill_ffwd" then
			self:LevelUp()
			self:Buy()
		end
		if not self.pending then self:Step(t, now) end
	end)
	if not ok then print("[tinker_bot] step error: " .. tostring(err)); self:Log("error", {msg = tostring(err), phase = self.phase}) end
	-- stuck guard: a phase that doesn't move on for 25 s goes home and starts over
	if self.phase ~= "lane" and self.phase ~= "wait" and self.phase ~= "fountain" and self.phase ~= "drill_ffwd"
			and now - self.phase_since > 40 then
		self:Log("stuck", {phase = self.phase})
		self.pending = nil
		self:SetPhase("go_home")
	end
	return 0.1
end

function TinkerBot:Snapshot(t)
	local h = self.hero
	local p = h:GetAbsOrigin()
	self:Log("snap", {x = math.floor(p.x), y = math.floor(p.y), hp = h:GetHealth(), mana = math.floor(h:GetMana()),
		max_mana = math.floor(h:GetMaxMana()), level = h:GetLevel(), lh = PlayerResource:GetLastHits(self.pid),
		gold = PlayerResource:GetGold(self.pid), nw = self:NetWorth(), phase = self.phase, station = self.station})
end

function TinkerBot:Step(t, now)
	local p = self.phase
	if p == "wait" then
		if t > -CFG.pregame + 1 then
			if CFG.drill then
				self:SetSpeed(CFG.drill.ffwd_speed)
				self.hero:AddNewModifier(self.hero, nil, "modifier_stunned", {})
				self.hero:AddNewModifier(self.hero, nil, "modifier_invulnerable", {})
				self:Log("phase", {to = "drill", reason = "fast-forward to 5:00 in fountain (like the F11 drill)"})
				self:SetPhase("drill_ffwd")
			else
				self:SetSpeed(CFG.lane_speed)
				self:SetPhase("lane")
			end
		end
		return
	end
	if p == "drill_ffwd" then
		if t >= CFG.drill.start_at - 3 then self:ApplyDrillState(now) end
		return
	end
	if p == "lane" then
		local rearm, keen = self:Ab("tinker_rearm"), self:Ab("tinker_keen_teleport")
		if rearm:GetLevel() > 0 and keen:GetLevel() > 0 then
			self:SetSpeed(CFG.speed)
			self:Log("phase", {to = "jungle", reason = "level 6: Rearm + Keen, Keen home now"})
			self:SetPhase("go_home")
		else
			return self:Lane(t, now)
		end
	end
	if self:Busy() then return end
	if p == "go_home" then return self:KeenTo("F", now) end
	if p == "go_station" then return self:KeenTo(self.go_to, now) end
	if p == "keening" then return self:Keening(t, now) end
	if p == "fountain" then return self:Fountain(t, now) end
	if p == "trip" then return self:Trip(t, now) end
end

-- ------------------------------------------------------------------ drill start: the player's 5:00 state
function TinkerBot:ApplyDrillState(now)
	local h, D = self.hero, CFG.drill
	for _ = h:GetLevel(), D.level - 1 do h:HeroLevelUp(false) end
	for name, lvl in pairs(D.abilities) do
		local ab = h:FindAbilityByName(name)
		if ab then ab:SetLevel(lvl) end
	end
	h:SetAbilityPoints(0)
	for slot = 0, 16 do
		local it = h:GetItemInSlot(slot)
		if it then h:RemoveItem(it) end
	end
	for _, name in ipairs(D.items) do h:AddItemByName(name) end
	PlayerResource:SetGold(self.pid, D.gold, false)
	PlayerResource:SetGold(self.pid, 0, true)
	h:RemoveModifierByName("modifier_stunned")
	h:RemoveModifierByName("modifier_invulnerable")
	h:SetHealth(h:GetMaxHealth())
	h:SetMana(h:GetMaxMana())
	for i = 0, h:GetAbilityCount() - 1 do
		local ab = h:GetAbilityByIndex(i)
		if ab then ab:EndCooldown() end
	end
	self:SetSpeed(CFG.speed)
	self.keened = true                    -- buys happen in fountain from here on
	self.drill_started = true
	if CFG.manual then
		self.enabled = false                          -- you play: the drill only sets up 5:00
		GameRules:SendCustomMessage("5:00 - your turn. Keen, fountain, go. The drill ends at 10:00.", 0, 0)
	end
	self:Log("drill_start", {state = D.source, nw = self:NetWorth(), level = h:GetLevel(), mana = math.floor(h:GetMaxMana())})
	self.fountain_at = now
	self.asked_station = false
	self.next_station = nil
	self:SetPhase("fountain")
end

-- ------------------------------------------------------------------ laning (0:00 - level 6): code only
function TinkerBot:EnemyTowers()
	if not self.towers or GameRules:GetGameTime() > (self.towers_at or 0) + 10 then
		self.towers = {}
		for _, tw in ipairs(Entities:FindAllByClassname("npc_dota_tower")) do
			if tw:GetTeamNumber() == DOTA_TEAM_BADGUYS and tw:IsAlive() then table.insert(self.towers, tw:GetAbsOrigin()) end
		end
		self.towers_at = GameRules:GetGameTime()
	end
	return self.towers
end

function TinkerBot:NearEnemyTower(pos, r)
	for _, tp in ipairs(self:EnemyTowers()) do if dist2(pos, tp) < (r or 900) then return true end end
	return false
end

local function safe(fn, default)
	local ok, v = pcall(fn)
	if ok and v ~= nil then return v end
	return default
end

-- damage per second each creep is taking right now (from its HP over the last ~0.8 s)
function TinkerBot:TrackHP(units, now)
	self.hp_hist = self.hp_hist or {}
	self.dps = self.dps or {}
	for _, u in ipairs(units) do
		local id = u:entindex()
		local hist = self.hp_hist[id] or {}
		table.insert(hist, {now, u:GetHealth()})
		while #hist > 1 and now - hist[1][1] > 0.8 do table.remove(hist, 1) end
		self.hp_hist[id] = hist
		local dt = now - hist[1][1]
		self.dps[id] = dt > 0.15 and math.max(0, (hist[1][2] - u:GetHealth()) / dt) or 0
	end
end

function TinkerBot:Lane(t, now)
	local h = self.hero
	local p = h:GetAbsOrigin()
	local laser = self:Ab("tinker_laser")
	local march = self:Ab("tinker_march_of_the_machines")
	if self:Busy() then return end
	-- HP safety: Faerie Fire under 35 %, walk home under 25 % (back in lane at 90 %)
	local hp = h:GetHealth() / h:GetMaxHealth()
	if self.retreat then
		if hp >= 0.9 then self.retreat = false else
			if dist2(p, self.fountain) > 400 then self:Move(self.fountain) end
			return
		end
	end
	if hp < 0.35 then
		for slot = 0, 5 do
			local it = h:GetItemInSlot(slot)
			if it and it:GetName() == "item_faerie_fire" and it:IsCooldownReady() then
				self:Order({OrderType = DOTA_UNIT_ORDER_CAST_NO_TARGET, AbilityIndex = it:entindex()})
				self:Log("cast", {ability = "faerie_fire", hp = h:GetHealth()})
				return
			end
		end
	end
	if hp < 0.25 then
		self.retreat = true
		self:Log("retreat", {hp = h:GetHealth()})
		self:Move(self.fountain)
		return
	end
	local enemies = {}
	for _, u in ipairs(self:Units(p, 1300, false)) do
		if not self:NearEnemyTower(u:GetAbsOrigin(), 900) then table.insert(enemies, u) end   -- never under their tower
	end
	if #enemies == 0 then
		if dist2(p, vec(CFG.lane_spot)) > 250 then self:Move(vec(CFG.lane_spot)) end
		return
	end
	local dmg = h:GetAverageTrueAttackDamage(nil) * 0.97
	self:TrackHP(enemies, now)
	-- committed to a last hit: hands off until the swing lands (re-ordering restarts the 0.35 s wind-up)
	if self.lh_target and not self.lh_target:IsNull() and self.lh_target:IsAlive() and now - (self.lh_at or 0) < 0.75 then return end
	local aps = safe(function() return h:GetAttacksPerSecond(false) end, 1 / 1.7)
	local range = safe(function() return h:Script_GetAttackRange() end, 500)
	local speed = safe(function() return h:GetIdealSpeed() end, 305)
	local ready = safe(function() return h:AttackReady() end, true)
	local windup = 0.35 / math.max(0.5, aps * 1.7)                 -- Tinker's 0.35 s attack point, scaled by attack speed
	local best, best_margin = nil, nil
	for _, u in ipairs(enemies) do
		local armor = u:GetPhysicalArmorValue(false)
		local hit = dmg * (1 - (0.06 * armor) / (1 + 0.06 * math.abs(armor)))
		local d = dist2(p, u:GetAbsOrigin())
		local walk = math.max(0, d - range - 20) / speed
		local ready_in = ready and 0 or 0.4
		local t_hit = ready_in + walk + windup + math.max(0, d - walk * speed) / 900 + 0.1
		local hp = u:GetHealth()
		local pred = hp - (self.dps[u:entindex()] or 0) * t_hit
		if (hp <= hit and pred > -hit * 0.5) or (t_hit <= 0.8 and pred > 0 and pred <= hit * 0.9 and hp <= hit * 1.7) then
			local margin = hit - pred
			if not best or margin < best_margin then best, best_margin = u, margin end
		end
	end
	if best then
		self.lh_target, self.lh_at = best, now
		self:Attack(best)
		self:Log("last_hit_try", {unit = best:GetUnitName(), hp = best:GetHealth(), dps = math.floor(self.dps[best:entindex()] or 0)})
		return
	end
	if self:Ready(laser) and h:GetMana() > h:GetMaxMana() * 0.7 then
		for _, u in ipairs(enemies) do
			if u:GetUnitName():find("ranged") and u:GetHealth() <= CFG.laser_dmg[laser:GetLevel()] then
				self:CastTarget(laser, u)
				self:Log("cast", {ability = "laser", unit = u:GetUnitName(), hp = u:GetHealth(), why = "ranged creep last hit"})
				return
			end
		end
	end
	-- March a fresh wave (4+ creeps, mostly healthy) when the mana is there: the robots last-hit the wave for us.
	-- From 4:15 also shove whatever is left before Keen (Immortals push the wave in before leaving lane)
	local fresh, hpsum, hpmax = 0, 0, 0
	for _, u in ipairs(enemies) do
		if dist2(p, u:GetAbsOrigin()) < 900 then fresh = fresh + 1; hpsum = hpsum + u:GetHealth(); hpmax = hpmax + u:GetMaxHealth() end
	end
	local wave_ok = fresh >= 4 and hpsum > 0.6 * hpmax and march:GetLevel() >= 2 and h:GetMana() >= math.max(0.55 * h:GetMaxMana(), march:GetManaCost(-1) + 100)
	if self:Ready(march) and (wave_ok or (t >= 255 and #enemies >= 3 and h:GetMana() > 250)) then
		local c = enemies[1]:GetAbsOrigin() - p
		c.z = 0
		local d = c:Normalized()
		local a = math.rad(45)
		return self:MarchDir(Vector(d.x * math.cos(a) - d.y * math.sin(a), d.x * math.sin(a) + d.y * math.cos(a), 0),
			t >= 255 and "shove before Keen" or "the robots last-hit the wave")
	end
	if h:GetAttackTarget() and now - (self.lh_at or 0) > 1.5 then h:Stop() end
	-- stand ~350 behind our creeps, on the far side from the enemy wave
	local own = FindUnitsInRadius(DOTA_TEAM_GOODGUYS, p, nil, 1200, DOTA_UNIT_TARGET_TEAM_FRIENDLY,
		DOTA_UNIT_TARGET_BASIC, DOTA_UNIT_TARGET_FLAG_NONE, FIND_CLOSEST, false)
	local ex, ey = 0, 0
	for _, u in ipairs(enemies) do local q = u:GetAbsOrigin(); ex = ex + q.x; ey = ey + q.y end
	local ec = Vector(ex / #enemies, ey / #enemies, 0)
	local spot = vec(CFG.lane_spot)
	local ox, oy, n = 0, 0, 0
	for _, u in ipairs(own) do
		if not u:IsHero() and not u:IsBuilding() then local q = u:GetAbsOrigin(); ox = ox + q.x; oy = oy + q.y; n = n + 1 end
	end
	if n > 0 then
		local oc = Vector(ox / n, oy / n, 0)
		local back = oc - ec
		back.z = 0
		if back:Length2D() < 1 then back = self.fountain - oc; back.z = 0 end
		spot = oc + back:Normalized() * 150
	else
		spot = ec + (self.fountain - ec):Normalized() * 750           -- no creeps of ours: keep out of their reach
	end
	if self:NearEnemyTower(spot, 950) then spot = vec(CFG.lane_spot) end
	if dist2(p, spot) > 200 then self:Move(spot) end
end

-- ------------------------------------------------------------------ Keen
function TinkerBot:KeenTo(st, now)
	local keen, rearm = self:Ab("tinker_keen_teleport"), self:Ab("tinker_rearm")
	local march = self:Ab("tinker_march_of_the_machines")
	if st ~= "F" and not march:IsCooldownReady() and self:Ready(rearm) then
		self:CastNo(rearm)
		self:Log("cast", {ability = "rearm", why = "refresh March before hopping to " .. st})
		return
	end
	if not self:Ready(keen) then
		if not keen:IsCooldownReady() and self:Ready(rearm) then
			self:CastNo(rearm)
			self:Log("cast", {ability = "rearm", why = "refresh Keen"})
		end
		return
	end
	local target = st == "F" and self.fountain or vec(CFG.stations[st].land)
	self.station = st
	self.keen_from = self.hero:GetAbsOrigin()
	self.keen_at = now
	self.keened = true
	self:CastPos(keen, target)
	self:Log("keen", {to = st, mana = math.floor(self.hero:GetMana())})
	self:SetPhase("keening")
end

function TinkerBot:Keening(t, now)
	if dist2(self.hero:GetAbsOrigin(), self.keen_from) > 1200 then return self:Landed(t, now) end
	if now - self.keen_at > 6 then
		self:Log("keen_failed", {station = self.station})
		if self.station ~= "F" then self.last_cleared[self.station] = self:Minute() end
		self:SetPhase(self:InFountain() and "fountain" or "go_home")
		self.fountain_at = now
	end
end

function TinkerBot:Landed(t, now)
	local st = self.station
	local lp = self.hero:GetAbsOrigin()
	self:Log("landed", {station = st, mana = math.floor(self.hero:GetMana()), x = math.floor(lp.x), y = math.floor(lp.y),
		off_target = st ~= "F" and math.floor(dist2(lp, vec(CFG.stations[st].land))) or nil})
	-- book the camps we just left: cleared if the robots finished them while we channelled
	local prev = self.trip
	if prev and not prev.queued then
		prev.queued = true
		prev.stop = t
		prev.stop_minute = self:Minute()
		table.insert(self.bookings, {trip = prev, at = now + 3.5})
	end
	if st == "F" then
		self.fountain_at = now
		self.next_station = nil
		self.asked_station = false
		self:SetPhase("fountain")
	else
		self.trip = {station = st, start = t, lh0 = PlayerResource:GetLastHits(self.pid), marches = 0, lasers = 0,
			plan = {}, i = 1, landed_at = now}
		for tok in CFG.stations[st].plan:gmatch("%S+") do table.insert(self.trip.plan, tok) end
		if CFG.two_marches_at_4 and st ~= "B" and self:Ab("tinker_march_of_the_machines"):GetLevel() >= 4 then  -- tested: fewer kills
			-- March maxed: two Marches, then Laser the tanky creeps instead of a third March
			local p2, ms = {}, 0
			for _, tok in ipairs(self.trip.plan) do
				table.insert(p2, tok)
				if tok == "M" then ms = ms + 1 end
				if ms == 2 then break end
			end
			self.trip.plan = p2
		end
		table.insert(self.trips, self.trip)
		self:SetPhase("trip")
	end
end

function TinkerBot:Book(prev)
	prev.lh = PlayerResource:GetLastHits(self.pid) - prev.lh0
	local left = prev.station ~= "B" and self:StationCreeps(prev.station) or 0
	for _, c in ipairs(self.camps or {}) do
		if c.st == prev.station then
			c.n = #self:Units(c.pos, 650, true)
			c.seen, c.seen_n, c.seen_minute = GameRules:GetGameTime(), c.n, self:Minute()
			-- two trips in a row with 0-1 kills and creeps still there: the plan's Marches don't reach them (bot run
			-- 2026-09-30: D's SW camp kept 6 creeps / 3,400 HP through four trips). Stop counting them.
			-- (one bad trip isn't enough: C went +1 then +5 in the same run)
			c.low = prev.station ~= "B" and prev.lh <= 1 and c.n > 0 and (c.low or 0) + 1 or 0
			if c.low >= 2 and not c.stuck then
				c.stuck, c.stuck_at = c.n, GameRules:GetGameTime()
				self:Log("camp_stuck", {station = c.st, creeps = c.n})
			end
		end
	end
	if prev.station ~= "B" and left == 0 then
		self.last_cleared[prev.station] = math.max(self.last_cleared[prev.station] or -1, prev.stop_minute)
	elseif prev.station ~= "B" then
		self.leftover = self.leftover or {}
		self.leftover[prev.station] = {n = left, minute = self:Minute()}
	end
	self:Log("trip", {station = prev.station, seconds = math.floor(prev.stop - prev.start), last_hits = prev.lh,
		marches = prev.marches, lasers = prev.lasers, creeps_left = left})
end

-- ------------------------------------------------------------------ fountain: Bottle, Rearm, Bottle, Keen
function TinkerBot:Fountain(t, now)
	local h = self.hero
	local keen, rearm = self:Ab("tinker_keen_teleport"), self:Ab("tinker_rearm")
	-- ask once the camps we just left are recounted (3.5 s after landing): asking on landing saw the creeps the
	-- robots were still killing, and 72 of 72 same-minute repeat trips went camp -> fountain -> same camp
	if not self.asked_station and #self.bookings == 0 then
		self.asked_station = true
		self:StationDecision(t)                   -- in the background: Jev answers while we Bottle and Rearm
	end
	if self:UseBottle("fountain refills it") then return end
	if not keen:IsCooldownReady() then
		if self:Ready(rearm) then self:CastNo(rearm); self:Log("cast", {ability = "rearm", why = "refresh Keen in fountain"}) end
		return
	end
	local st = self.next_station
	if not st then return end
	local dwell = now - self.fountain_at
	if st == "F" then                                              -- wait for camps / re-ask in a few seconds
		if dwell > 5 then self.asked_station = false; self.next_station = nil; self.fountain_at = now - 3 end
		return
	end
	-- leave when the whole trip's mana is there: the Keen out (the channel in fountain refills only ~15) + the plan
	-- your 7 s / Immortal 7.5 s rule: leave at once with the whole trip's mana, else at 7.5 s if two Marches'
	-- worth is there (Keen out + M + R + M + Keen home), else wait up to 11 s
	local mc, rc, kc = self:Costs()
	local have = h:GetMana() - kc + self:BottleCharges() * 60      -- (the refill during the Keen channel is too unreliable to count on)
	local two = 2 * mc + rc + kc + self:Reserve()        -- same rule the camp uses for the 2nd March
	-- (Immortals' 7.5 s is landing -> next landing incl. the 3 s Keen: ~4.5 s of actual waiting)
	if have >= self:PlanNeed(st) + self:BottleCharges() * 60 or h:GetMana() >= h:GetMaxMana() * 0.97
			or (dwell >= 3.5 and have >= two) or dwell >= 7 then
		self.go_to = st
		self:SetPhase("go_station")
	end
end

-- ------------------------------------------------------------------ station decision (Jev)
function TinkerBot:StationFacts(t, mana_now)
	local h = self.hero
	local wave = self:MidWave()
	local camps, recent = {}, {}
	for _, st in ipairs({"A", "C", "D", "E"}) do
		camps[st] = {ready = self:CampReady(st), expected_creeps = self:StationValue(st),
			only_leftovers_blocking_the_spawn = self:CleanupReady(st)}
	end
	for i = math.max(1, #self.trips - 3), #self.trips do
		local tr = self.trips[i]
		if tr then table.insert(recent, {to = tr.station, last_hits = tr.lh or 0, seconds = math.floor((tr.stop or t) - tr.start)}) end
	end
	local charges = self:BottleCharges()
	return {
		game_clock = clockstr(t),
		seconds_until_camps_respawn = 60 - math.floor(t % 60),
		tinker = {location = self:InFountain() and "fountain" or (self.station or "?"), level = h:GetLevel(),
			mana = math.floor(mana_now), max_mana = math.floor(h:GetMaxMana()), bottle_charges = charges,
			march_level = self:Ab("tinker_march_of_the_machines"):GetLevel(), laser_level = self:Ab("tinker_laser"):GetLevel()},
		camps = camps,
		mid_wave = wave and {visible = true, creeps = wave.n, pushing_into_your_tower = wave.threat} or {visible = false},
		last_trips = recent,
	}, wave
end

-- the Immortal routing rule (matches 51% of 295 Immortal decisions; Jev's best prompt matched 45-48%):
-- a camp trip is followed by the mid wave; a wave by the ancients (March 4) or the mid pair; D/E fill in
function TinkerBot:StationRules(t, wave, mana)
	local h = self.hero
	local last = self.trips[#self.trips] and self.trips[#self.trips].station or nil
	local march = self:Ab("tinker_march_of_the_machines"):GetLevel()
	if wave and wave.threat then return "B" end
	local camp = last == "A" or last == "C" or last == "D" or last == "E"
	if (camp or last == nil) and wave and (wave.threat or wave.n >= CFG.wave_min_creeps) then return "B" end
	if self:CampReady("C") and march >= 4 and mana >= 450 then return "C" end
	if self:CampReady("A") then return "A" end
	if self:CampReady("C") and march >= 4 then return "C" end
	if self:CampReady("D") then return "D" end
	if t >= 510 and self:CampReady("E") then return "E" end
	if wave and wave.n >= CFG.wave_min_creeps then return "B" end
	-- nothing full: clear the camp with the most leftovers so its next :00 spawn can land
	local best, bv = nil, 0
	for _, st in ipairs({"A", "C", "D"}) do
		if self:CleanupReady(st) and (st ~= "C" or march >= 4) and self:StationValue(st) > bv then best, bv = st, self:StationValue(st) end
	end
	return best or "F"
end

function TinkerBot:StationDecision(t)
	local h = self.hero
	local mana = self:InFountain() and math.min(h:GetMaxMana(), h:GetMana() + 250) or h:GetMana()   -- fountain refills before leaving
	local facts, wave = self:StationFacts(t, mana)
	local rules = self:StationRules(t, wave, mana)
	local options = {}
	local in_f = self:InFountain()
	local here = (not in_f) and self.trip and self.trip.station or nil
	local cleanup = {}
	for _, s in ipairs({"A", "C", "D", "E"}) do
		-- from the field, only stations the mana on hand can clear (from fountain the refill covers it)
		local affordable = in_f or h:GetMana() + self:BottleCharges() * 60 >= self:PlanNeed(s)
		if s ~= here and affordable and (s ~= "C" or self:Ab("tinker_march_of_the_machines"):GetLevel() >= 4) then
			if self:CampReady(s) then table.insert(options, s)
			elseif self:CleanupReady(s) then table.insert(cleanup, s) end
		end
	end
	-- leftover-only camps only when no full one is up, like the rules (run 7: Jev took A's 3 leftovers over
	-- D's 8 fresh creeps twice, 0 kills each)
	if #options == 0 then options = cleanup end
	if wave and here ~= "B" and (in_f or h:GetMana() + self:BottleCharges() * 60 >= self:PlanNeed("B")) then table.insert(options, "B") end
	table.insert(options, "F")
	if wave and wave.threat then options = {"B"} end                    -- a wave at your tower is always taken
	if rules == here then rules = "F" end
	if not contains(options, rules) then table.insert(options, rules) end
	local in_fountain = self:InFountain()
	if not in_fountain then self:SetPhase("deciding") end
	self:Decide("station", facts, options, rules, function(pick, src)
		if CFG.station_by_rules and pick ~= rules then src = "rules (jev shadow: " .. pick .. ")"; pick = rules end
		self:Log("decision", {what = "station", pick = pick, rules = rules, src = src, options = options,
			wave = wave and wave.n or 0, wave_threat = wave and wave.threat or nil})
		if in_fountain then
			self.next_station = pick
		elseif pick == "F" then
			self:SetPhase("go_home")
		else
			self.go_to = pick
			self:SetPhase("go_station")
		end
	end, in_fountain)
end

-- ------------------------------------------------------------------ a station trip: walk, M b R M b R M, finish, Keen
function TinkerBot:Targets(tr)
	local p = self.hero:GetAbsOrigin()
	if tr.station == "B" then return self:Units(p, 1500, false) end
	return self:Units(p, 1300, true)
end

function TinkerBot:OutOfSpawnBox(t)
	local sec = t % 60
	if sec < 56.5 or self:Busy() then return false end
	local p = self.hero:GetAbsOrigin()
	for _, c in ipairs(self.camps or {}) do
		local d = dist2(p, c.pos)
		if d < 560 then
			local away = p - c.pos
			away.z = 0
			if away:Length2D() < 1 then away = Vector(1, 0, 0) end
			self:Move(c.pos + away:Normalized() * 750)
			if not self.box_logged or self.box_logged ~= self:Minute() then
				self.box_logged = self:Minute()
				self:Log("spawn_box", {why = "step out of the camp before :00 so it can spawn"})
			end
			return true
		end
	end
	return false
end

function TinkerBot:StackStep(t, now)
	local tr = self.trip
	if not CFG.stack or tr.station == "B" or tr.station == "E" then return false end
	local sec = t % 60
	local h = self.hero
	local march, laser = self:Ab("tinker_march_of_the_machines"), self:Ab("tinker_laser")
	local _, _, kc = self:Costs()
	local camp = {}
	for _, c in ipairs(self.camps or {}) do if c.st == tr.station then table.insert(camp, c) end end
	if #camp == 0 then return false end
	local cx, cy = 0, 0
	for _, c in ipairs(camp) do cx = cx + c.pos.x; cy = cy + c.pos.y end
	local centre = Vector(cx / #camp, cy / #camp, 0)
	local creeps = self:Units(centre, 900, true)
	if not tr.stack then
		-- start a stack only in the :50-:54 window, with creeps there and the mana for it + the Keen home
		if sec < 50 or sec > 54 or #creeps < 3 or tr.stacked_minute == self:Minute() then return false end
		local need = kc + (tr.station == "C" and laser:GetManaCost(-1) or march:GetManaCost(-1))
		if h:GetMana() < need then return false end
		if tr.station == "C" and not self:Ready(laser) then return false end
		if tr.station ~= "C" and not self:Ready(march) then return false end
		tr.stack = {step = 1}
		tr.stacked_minute = self:Minute()
		self:Log("stack", {station = tr.station, step = "start", creeps = #creeps})
	end
	local st = tr.stack
	if self:Busy() then return true end
	-- stand outside the spawn boxes while waiting
	if self:OutOfSpawnBox(t) then return true end
	if tr.station == "C" then
		-- ancients: Laser the ancient (fattest) at :53, right-click another at :54.5, then leave
		if st.step == 1 and sec >= 53 then
			local fat = nil
			for _, u in ipairs(creeps) do if not fat or u:GetMaxHealth() > fat:GetMaxHealth() then fat = u end end
			if fat then self:CastTarget(laser, fat); self:Log("stack", {station = "C", step = "laser the ancient", unit = fat:GetUnitName()}) end
			st.step = 2
		elseif st.step == 2 and sec >= 54.5 then
			local other = nil
			for _, u in ipairs(creeps) do if u:GetHealth() > 0 and (not other or u:GetMaxHealth() < other:GetMaxHealth()) then other = u end end
			if other then self:Attack(other); self:Log("stack", {station = "C", step = "hit the other one", unit = other:GetUnitName()}) end
			st.step = 3; st.at = now
		elseif st.step == 3 and now - st.at > 0.6 then
			st.step = 4
			self:Log("stack", {station = "C", step = "leave"})
			self:SetPhase("go_home")
		end
		return true
	end
	-- normal camps: March at :55 facing back the way we came (away from the camp), then leave
	if st.step == 1 and sec >= 55 then
		local away = h:GetAbsOrigin() - centre
		away.z = 0
		if away:Length2D() < 1 then away = Vector(-1, 0, 0) end
		self:MarchDir(away:Normalized(), "stack: March at :55 facing away from the camp")
		st.step = 2; st.at = now
	elseif st.step == 2 and now - st.at > 0.7 then
		st.step = 3
		self:Log("stack", {station = tr.station, step = "leave"})
		self:SetPhase("go_home")
	end
	return true
end

function TinkerBot:Trip(t, now)
	local tr = self.trip
	local h = self.hero
	if self:StackStep(t, now) then return end
	if self:OutOfSpawnBox(t) then return end
	local S = CFG.stations[tr.station]
	local tok = tr.plan[tr.i]
	local march, rearm, laser = self:Ab("tinker_march_of_the_machines"), self:Ab("tinker_rearm"), self:Ab("tinker_laser")
	local mc, rc, kc = self:Costs()
	local p = h:GetAbsOrigin()
	local targets = self:Targets(tr)
	local centre = nil
	if #targets > 0 then
		local cx, cy = 0, 0
		for _, u in ipairs(targets) do local q = u:GetAbsOrigin(); cx = cx + q.x; cy = cy + q.y end
		centre = Vector(cx / #targets, cy / #targets, 0)
	end
	local function nxt() tr.i = tr.i + 1; tr.issued = nil end
	if tok == nil then return self:FinishDecision(t, now, targets) end
	if tok == "walk" then
		local spot = S.stand and vec(S.stand) or centre
		if tr.station == "B" then
			if centre then spot = centre + (self.fountain - centre):Normalized() * 350 else spot = nil end
		end
		local close = centre and dist2(p, centre) < 450
		if spot == nil then
			if now - tr.landed_at > 3 then return self:FinishDecision(t, now, targets) end
			return
		end
		if dist2(p, spot) < 150 or close or now - tr.landed_at > 4.5 then return nxt() end
		if not tr.issued then tr.issued = now; self:Move(spot) end
		return
	end
	if tok == "M" then
		if tr.issued then
			if not march:IsCooldownReady() or now - tr.issued > 1.5 then
				tr.marches = tr.marches + 1
				return nxt()
			end
			return
		end
		if tr.queued_dir then
			if not march:IsCooldownReady() then                                   -- the queued March went off
				self.march_dir = tr.queued_dir
				self.last_march = now
				self:Log("cast", {ability = "march", why = (self:Aims(tr.station) and "aimed" or "turned 180") .. " (queued behind Rearm)"})
				tr.queued_dir = nil
				tr.marches = tr.marches + 1
				return nxt()
			end
			if now - tr.queued_at < 3.3 then return end                           -- channel just ended: give it a tick
			tr.queued_dir = nil                                                    -- didn't fire: cast normally
		end
		if not self:Ready(march) then return nxt() end
		local hpleft = 0
		for _, u in ipairs(targets) do hpleft = hpleft + u:GetHealth() end
		hpleft = hpleft + math.max(0, self:StationValue(tr.station) - #targets) * 450     -- creeps remembered but not in sight
		local need = (CFG.more_march_hp[tr.station] or {})[tr.marches]
		if tr.marches >= 2 and need and hpleft < need then                               -- Immortals leave here
			self:Log("skip", {why = string.format("%d HP left after %d Marches: Immortals stop here (< %d)", hpleft, tr.marches, need)})
			tr.i = #tr.plan + 1
			return
		end
		local expected = self:StationValue(tr.station)
		if tr.marches >= 1 and #targets <= 2 and #targets > 0 and expected <= 2 then     -- really 1-2 left: the Laser does it
			self:Log("skip", {why = "only " .. #targets .. " creeps left: Laser instead of another March"})
			tr.i = #tr.plan + 1
			return
		end
		if #targets == 0 then
			local to_spawn = 60 - t % 60
			if tr.station ~= "B" and tr.marches == 0 and to_spawn <= 7 and (tr.waited or 0) < 8 then
				if not tr.wait_logged then tr.wait_logged = true; self:Log("wait_spawn", {station = tr.station, seconds = math.floor(to_spawn)}) end
				tr.waited = (tr.waited or 0) + 0.1
				return                                                               -- the camp spawns at :00: wait for it
			end
			tr.i = #tr.plan + 1
			return                                                                   -- nothing here: don't March air
		end
		local dir
		if tr.station == "B" then
			-- diagonal across the lane: 45 deg off the lane axis, toward the wave
			local lane = Vector(1, 1, 0):Normalized()
			local side = centre and (centre - p) or lane
			side.z = 0
			local cross = lane.x * side.y - lane.y * side.x
			local a = math.rad(cross >= 0 and 45 or -45)
			dir = Vector(lane.x * math.cos(a) - lane.y * math.sin(a), lane.x * math.sin(a) + lane.y * math.cos(a), 0)
			if centre and (centre - p):Dot(dir) < 0 then dir = dir * -1 end
		elseif tr.marches == 0 then
			if S.stand and dist2(p, vec(S.stand)) < 400 then dir = yawdir(S.face)
			elseif centre then dir = (centre - p):Normalized()
			else dir = yawdir(S.face) end
		else
			dir = (self.march_dir or yawdir(S.face)) * -1                    -- turned 180 (Immortals: 139 of 304)
		end
		local why = tr.marches == 0 and "first March, Immortal facing" or "turned 180"
		if self:Aims(tr.station) then
			local d, share = self:BestMarchDir(p, targets)
			if d then dir, why = d, string.format("aimed: %d%% of the creeps in its path", math.floor(share * 100)) end
		end
		tr.issued = now
		return self:MarchDir(dir, why)
	end
	if tok == "b" then
		self:UseBottle("while the robots work")
		return nxt()
	end
	if tok == "R" then
		-- only if another March is planned and affordable with the mana to get home
		local more = false
		for j = tr.i + 1, #tr.plan do if tr.plan[j] == "M" or tr.plan[j] == "X" then more = true end end
		local bottle = self:BottleCharges() * 60                            -- the next 'b' refills this much
		if h:HasModifier("modifier_bottle_regeneration") then bottle = bottle + 35 end -- a sip already healing
		if not more then tr.i = #tr.plan + 1; return end
		if h:GetMana() + bottle - rc - mc - kc < self:Reserve() then
			self:Log("plan_end", {why = "mana", mana = math.floor(h:GetMana()), bottle = bottle, need = rc + mc + kc + self:Reserve()})
			tr.i = #tr.plan + 1; return
		end
		if #targets == 0 then
			self:Log("plan_end", {why = "no creeps in sight", expected = self:StationValue(tr.station),
				day = GameRules:IsDaytime(), vision = math.floor(h:GetCurrentVisionRange())})
			tr.i = #tr.plan + 1; return
		end
		if not tr.issued and tr.marches >= 1 and #targets <= 2 and self.last_march and now - self.last_march > 1.2 then
			self:Log("skip", {why = "only " .. #targets .. " creeps left: Laser instead of another March"})
			tr.i = #tr.plan + 1
			return
		end
		if tr.issued then
			if now - tr.issued >= 0.25 and not h:IsChanneling() then return nxt() end
			return
		end
		if not rearm:IsCooldownReady() then return end                        -- Rearm has a 5.5 s cooldown in 7.41
		if h:GetMana() < rc then tr.i = #tr.plan + 1; return end
		if tr.marches >= 1 and #targets <= 2 then
			self:Log("skip", {why = "only " .. #targets .. " creeps left: no Rearm, finish and go"})
			tr.i = #tr.plan + 1
			return
		end
		local hpleft = 0
		for _, u in ipairs(targets) do hpleft = hpleft + u:GetHealth() end
		hpleft = hpleft + math.max(0, self:StationValue(tr.station) - #targets) * 450     -- creeps remembered but not in sight
		local need = (CFG.more_march_hp[tr.station] or {})[tr.marches]
		if tr.marches >= 2 and need and hpleft < need then                               -- Immortals leave here
			self:Log("skip", {why = string.format("%d HP left after %d Marches: Immortals stop here (< %d)", hpleft, tr.marches, need)})
			tr.i = #tr.plan + 1
			return
		end
		tr.issued = now
		self:CastNo(rearm)
		self:Log("cast", {ability = "rearm", why = "refresh March"})
		-- action queue: shift-queue the next March so it fires the moment the channel ends
		local nextM = false
		for j = tr.i + 1, #tr.plan do if tr.plan[j] == "M" then nextM = true break elseif tr.plan[j] ~= "b" then break end end
		if nextM and tr.station ~= "B" and self.march_dir then
			local d = self.march_dir * -1
			if self:Aims(tr.station) then d = self:BestMarchDir(h:GetAbsOrigin(), targets) or d end
			self:Order({OrderType = DOTA_UNIT_ORDER_CAST_POSITION, AbilityIndex = march:entindex(),
				Position = h:GetAbsOrigin() + d * 250, Queue = 1})
			tr.queued_dir = d
			tr.queued_at = now
		end
		return
	end
	if tok == "L" then
		if tr.issued then
			if not laser:IsCooldownReady() or now - tr.issued > 1.5 then tr.lasers = tr.lasers + 1; return nxt() end
			return
		end
		if not self:Ready(laser) or #targets == 0 then return nxt() end
		local ldmg = CFG.laser_dmg[laser:GetLevel()] or 0
		local best, why = nil, "kills it"
		for _, u in ipairs(targets) do                                   -- a creep it kills (the biggest such) first
			if u:GetHealth() <= ldmg and (not best or u:GetHealth() > best:GetHealth()) then best = u end
		end
		if not best and tr.station == "C" then why = "fattest (ancients)" end
		if not best then
			if why ~= "fattest (ancients)" then why = "fattest one left" end
			for _, u in ipairs(targets) do if not best or u:GetHealth() > best:GetHealth() then best = u end end
		end
		tr.issued = now
		self:CastTarget(laser, best)
		self:Log("cast", {ability = "laser", unit = best:GetUnitName(), hp = best:GetHealth(), why = why})
		return
	end
	if tok == "A" then
		if #targets == 0 then return nxt() end
		if tr.issued and now - tr.issued > 3 then return nxt() end
		local weak = targets[1]
		for _, u in ipairs(targets) do if u:GetHealth() < weak:GetHealth() then weak = u end end
		if not tr.issued or (tr.atk_unit ~= weak and now - (tr.atk_at or 0) > 1.3) then     -- one order per target: re-ordering cancels the swing
			tr.issued = tr.issued or now
			tr.atk_unit, tr.atk_at = weak, now
			self:Attack(weak)
			self:Log("cast", {ability = "attack", unit = weak:GetUnitName(), hp = weak:GetHealth(), why = "finish the camp"})
		end
		return
	end
	if tok == "RL" then
		if tr.issued then
			if now - tr.issued >= 0.25 and not h:IsChanneling() then return nxt() end
			return
		end
		if not rearm:IsCooldownReady() then return end
		tr.issued = now
		self:CastNo(rearm)
		self:Log("cast", {ability = "rearm", why = "refresh Laser for the tanky one"})
		return
	end
	if tok == "X" then
		if tr.issued then
			if not march:IsCooldownReady() or now - tr.issued > 1.5 then tr.marches = tr.marches + 1; return nxt() end
			return
		end
		if not self:Ready(march) then return nxt() end
		local aim = centre
		if not aim then
			local best
			for _, c in ipairs(self.camps or {}) do
				if c.st == tr.station and c.n > 0 and (not best or dist2(p, c.pos) < dist2(p, best)) then best = c.pos end
			end
			aim = best
		end
		local dir = aim and (aim - p) or (self.march_dir or yawdir(S.face or 0))
		dir.z = 0
		if dir:Length2D() < 1 then dir = yawdir(S.face or 0) end
		if #targets > 0 and self:Aims(tr.station) then dir = self:BestMarchDir(p, targets) or dir end
		tr.issued = now
		return self:MarchDir(dir:Normalized(), "one extra March, then leave")
	end
	if tok == "K" then
		return self:LeaveDecision(t, now)
	end
	nxt()
end

function TinkerBot:PrefetchStation(t)
	local tr = self.trip
	if not tr or tr.prefetch_asked then return end
	tr.prefetch_asked = true
	local h = self.hero
	local _, _, kc = self:Costs()
	local arrive = h:GetMana() + self:BottleCharges() * 60 - kc                -- what's left after the Keen out
	local facts, wave = self:StationFacts(t, arrive)
	local rules = self:StationRules(t, wave, arrive)
	local options = {"F"}
	local full = arrive >= 0.9 * h:GetMaxMana()                                -- Immortals go home between trips
	for _, st in ipairs({"A", "C", "D", "E"}) do
		if full and st ~= tr.station and self:CampReady(st) and arrive >= self:PlanNeed(st) then table.insert(options, st) end
	end
	if full and wave and tr.station ~= "B" and arrive >= self:PlanNeed("B") then table.insert(options, "B") end
	if not contains(options, rules) then rules = "F" end
	self:Decide("station", facts, options, rules, function(pick, src)
		if CFG.station_by_rules and pick ~= rules then src = "rules (jev shadow: " .. pick .. ")"; pick = rules end
		tr.prefetch = {pick = pick, at = GameRules:GetGameTime()}
		self:Log("decision", {what = "station", pick = pick, rules = rules, src = src, options = options, prefetched = true})
	end, true)
end

-- after the Marches: finish the camp, then leave (the robots keep working during the Keen channel).
--   a creep one Laser kills -> Laser it;  a tanky creep -> Laser the tankiest, Rearm + Laser again if it lives;
--   3+ creeps with lots of HP -> one more Rearm + March;  nothing worth it -> Keen away
function TinkerBot:IsTanky(u, ldmg)
	local n = u:GetUnitName()
	return u:GetHealth() > math.max(350, ldmg * 0.9) or n:find("ancient") or n:find("big") or n:find("khan")
		or n:find("golem") or n:find("granite") or n:find("prowler") or n:find("thunder")
end

function TinkerBot:FinishDecision(t, now, targets)
	local tr = self.trip
	self:PrefetchStation(t)
	if CFG.leave_at_once then
		local laser = self:Ab("tinker_laser")
		local ldmg = CFG.laser_dmg[laser:GetLevel()] or 0
		local killable = false
		for _, u in ipairs(targets) do if u:GetHealth() <= ldmg then killable = true end end
		if killable and not tr.kill_lasered and self:Ready(laser) then
			tr.kill_lasered = true
			table.insert(tr.plan, "L")                                      -- a creep the Laser kills: take it
			return
		end
		if tr.station == "C" and (tr.lasers or 0) < 1 and self:Ready(laser) and #targets > 0 and not tr.c_lasered then
			tr.c_lasered = true
			table.insert(tr.plan, "L")                                      -- the fattest ancient, while the robots work
			return
		end
		-- a few creeps left block the camp's next :00 spawn (bot runs 2026-09-30), so a small remainder is worth
		-- a few seconds of right-clicks next to the robots; a big one isn't (Keen out, a cleanup trip gets it later)
		if tr.station ~= "B" and #targets >= 1 and #targets <= 3 and (tr.finish or 0) < 2 then
			local hp = 0
			for _, u in ipairs(targets) do hp = hp + u:GetHealth() end
			if hp <= (CFG.finish_hp or 700) then
				tr.finish = (tr.finish or 0) + 1
				self:Log("finish", {left = #targets, hp = hp, round = tr.finish})
				table.insert(tr.plan, "A")                                  -- up to 3 s, then this decision again
				return
			end
		end
		table.insert(tr.plan, "K")
		return
	end
	if self.last_march and now - self.last_march < 1.6 and #targets > 0 then return end
	tr.rounds = (tr.rounds or 0) + 1
	local h = self.hero
	local laser, rearm = self:Ab("tinker_laser"), self:Ab("tinker_rearm")
	local mc, rc, kc = self:Costs()
	local lc = laser:GetManaCost(-1)
	local ldmg = CFG.laser_dmg[laser:GetLevel()] or 0
	local expected = tr.station ~= "B" and self:StationValue(tr.station) or 0
	if tr.rounds > 4 or (#targets == 0 and expected == 0) then
		table.insert(tr.plan, "K")
		return
	end
	local left, total, killable, tanky = {}, 0, 0, 0
	for _, u in ipairs(targets) do
		local nm = u:GetUnitName():gsub("npc_dota_neutral_", ""):gsub("npc_dota_creep_", "")
		table.insert(left, {name = nm, hp = u:GetHealth(), max_hp = u:GetMaxHealth()})
		total = total + u:GetHealth()
		if u:GetHealth() <= ldmg then killable = killable + 1 end
		if self:IsTanky(u, ldmg) then tanky = tanky + 1 end
	end
	local mana = h:GetMana() + self:BottleCharges() * 60
	local reserve = self:Reserve()
	local can_rl = rearm:GetLevel() > 0 and not self:Ready(laser) and mana - rc - lc - kc >= reserve
	local can_rm = rearm:GetLevel() > 0 and mana - rc - mc - kc >= reserve
	-- Lasers close a camp (Immortals: ~0.5 per camp trip, ~0.9 at the ancients); at most 2 per trip, mana matters
	-- your finishing rules: 1-2 creeps left -> one Laser (the fattest at the ancients) and Keen out;
	-- 3+ creeps or a stack -> one extra March if the mana is there; else Keen out (the robots finish)
	local few = #targets >= 1 and #targets <= 2
	local stack = #targets >= 5                                                      -- a real stack, not a normal camp
	local options = {"keen_now"}
	if few and (tr.lasers or 0) < 1 and self:Ready(laser) then table.insert(options, "laser") end
	if stack and can_rm and (tr.extra or 0) < 1 then table.insert(options, "rearm_march") end
	local rules = "keen_now"
	if contains(options, "laser") then rules = "laser"
	elseif contains(options, "rearm_march") then rules = "rearm_march" end
	local state = {
		station = tr.station, marches_this_trip = tr.marches, game_clock = clockstr(t),
		creeps_left = left, creeps_left_count = #targets, creeps_left_total_hp = total, tanky_creeps = tanky,
		creeps_expected_in_camp_but_not_visible = math.max(0, expected - #targets),
		laser = {ready = self:Ready(laser), damage = ldmg, creeps_it_kills = killable},
		mana = math.floor(h:GetMana()), keep_for_home = reserve,
		mana_after_rearm_laser_and_keen = math.floor(mana - rc - lc - kc),
		mana_after_rearm_march_and_keen = math.floor(mana - rc - mc - kc),
		seconds_until_camps_respawn = 60 - math.floor(t % 60),
	}
	self:SetPhase("deciding")
	self:Decide("finish", state, options, rules, function(pick, src)
		self:Log("decision", {what = "finish", pick = pick, rules = rules, src = src, left = #targets, total_hp = total,
			tanky = tanky, options = options})
		if pick == "rearm_march" then
			tr.extra = (tr.extra or 0) + 1
			table.insert(tr.plan, "R"); table.insert(tr.plan, "X")
		elseif pick == "rearm_laser" then
			table.insert(tr.plan, "RL"); table.insert(tr.plan, "L")
		elseif pick == "laser" then
			table.insert(tr.plan, "L")
		else
			table.insert(tr.plan, "K")
		end
		self:SetPhase("trip")
	end)
end

-- leaving a station: home, or straight to another station when the mana is there
function TinkerBot:LeaveDecision(t, now)
	local h = self.hero
	local pf = self.trip and self.trip.prefetch
	if pf and now - pf.at < 12 then                                              -- decided while the robots worked
		self.trip.prefetch = nil
		local _, _, kc = self:Costs()
		if pf.pick ~= "F" and h:GetMana() + self:BottleCharges() * 60 - kc < self:PlanNeed(pf.pick) then
			self:Log("decision", {what = "station", pick = "F", rules = "F", src = "mana_check", was = pf.pick})
			return self:SetPhase("go_home")                                       -- Lasers since then spent the mana
		end
		if pf.pick == "F" or not (self:CampReady(pf.pick) or self:CleanupReady(pf.pick)) and pf.pick ~= "B" then
			return self:SetPhase("go_home")
		end
		self.go_to = pf.pick
		return self:SetPhase("go_station")
	end
	if h:GetMana() + self:BottleCharges() * 60 >= 0.9 * h:GetMaxMana() and #self.trips > 0 then
		return self:StationDecision(t)
	end
	self:SetPhase("go_home")
end
